name: PostgreSQL Backup to Google Drive

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

# هذا السطر لإخفاء تحذير Node.js واستخدام الإصدار الجديد
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PostgreSQL Client & Rclone
        run: sudo apt-get update && sudo apt-get install -y postgresql-client rclone

      - name: Generate Backup File
        run: |
          DATE=$(date +'%Y-%m-%d_%H-%M')
          FILENAME="dashboard_backup_$DATE.sql"
          
          # سحب الداتا بيز وضغطها
          pg_dump "${{ secrets.DATABASE_URL }}" > $FILENAME
          gzip $FILENAME
          
          echo "BACKUP_FILE=$FILENAME.gz" >> $GITHUB_ENV

      - name: Upload to Google Drive
        env:
          # تخزين الـ JSON كمتغير بيئة لتفادي مشاكل المسافات والأقواس
          GDRIVE_JSON: ${{ secrets.GDRIVE_CREDENTIALS }}
        run: |
          # كتابة ملف JSON
          echo "$GDRIVE_JSON" > sa.json
          
          # إعداد Rclone
          cat <<EOF > rclone.conf
          [gdrive]
          type = drive
          scope = drive
          service_account_file = sa.json
          root_folder_id = ${{ secrets.GDRIVE_FOLDER_ID }}
          EOF
          
          # الرفع مع طباعة التفاصيل في حالة الخطأ (-v)
          rclone --config rclone.conf copy ${{ env.BACKUP_FILE }} gdrive: -v